<?php
class plugin_Szkaluje implements IPlugin {
	private $szkaluj_array = array();
	private $mitsuba;

	public function __construct($conn, &$mitsuba)
	{
		$this->mitsuba = $mitsuba;

		$this->szkaluj_array = array("%1\$s rozpierdolił pasiekę", 
			"%1\$s przechodzi na czerwonym przez ulicę", 
			"%1\$s nie spuszcza wody w toaletach publicznych", 
			"%1\$s po sikaniu nie myje rąk po czym wita się ze wszystkimi współpracownikami", 
			"%1\$s pisał sam sobie zwolnienia z wuefu", 
			"%1\$s nie je śniadania", 
			"%1\$s mimo obietnic złożonych matce, zaraz po wyjściu z domu zdejmował czapkę i chował do tornistra", 
			"%1\$s nie nosi kaleson", 
			"%1\$s podczas grillowania w parku oddawał mocz w krzakach", 
			"%1\$s przeklina", 
			"%1\$s gdy miał 13 lat upił tacie pianę z piwa gdy nie patrzył", 
			"%1\$s trzaska drzwiami", 
			"%1\$s będąc niepełnoletnim kupił w kiosku 3 sztuki papierosów po czym przestraszył się i spuścił je w klozecie", 
			"%1\$s nie podmywa się po sraniu.", 
			"%1\$s będąc w szkole podstawowej zjadał gile z nosa. Na prośby nauczycielek by przestał to robić odpowiadał, że to jak narkotyk.", 
			"%1\$s nie odmawia pacierza przed snem", 
			"%1\$s jest niegodny zaufania", 
			"%1\$s walił konia w łóżku swoich starych", 
			"%1\$s ciągnął koleżanki za warkoczyki w przedszkolu", 
			"%1\$s kradnie prąd z klatki schodowej", 
			"%1\$s obraził PolishAdama28 niewybrednymi słowami", 
			"%1\$s kiedyś dostał za dużo reszty w sklepie spożywczym i nie powiedział ekspedientce", 
			"%1\$s podkrada spinacze sąsiadom", 
			"%1\$s zrobił aferę w poznańskim radiu", 
			"%1\$s specjalnie wpisuje błędna kapczę", 
			"%1\$s kradnie sprzęty biurowe", 
			"%1\$s nie myje po sobie naczyn", 
			"%1\$s przejeżdża na pomarańczowym", 
			"%1\$s nie ustępuje starszym w trawajach", 
			"%1\$s chodzi nago po domu.", 
			"%1\$s zajebał mi szlugi", 
			"%1\$s umyślnie podawał kolegom na sprawdzianach złe rozwiązania", 
			"%1\$s dzwonił pod wszystkie numery domofonem po czym uciekał gdzie pieprz rośnie", 
			"%1\$s nie czyta książek", 
			"%1\$s od czasu do czasu nie myje zębów przed pójściem spać", 
			"%1\$s sika na siedząco", 
			"%1\$s podgląda jaki PIN wstukują ludzie w bankomacie", 
			"%1\$s bawi się analnie", 
			"%1\$s uwięził i zamordował rodzinę carską", 
			"%1\$s często chodzi cały dzień bardzo spocony.", 
			"%1\$s będą u kogoś gościem kradnie zastawę stołową", 
			"%1\$s puszcza ciche bąki jeżdżąc komunikacją miejską", 
			"%1\$s zostawia warzywa na talerzu", 
			"%1\$s zostawia surówkę niezjedzoną.", 
			"%1\$s nie seeduje torrentów", 
			"%1\$s minusuje konstruktywne komentarze", 
			"%1\$s przykleja kozy z nosa pod blat biurka", 
			"%1\$s mlaska przy jedzeniu", 
			"%1\$s pogardliwe patrzy na starsze i schorowane osoby", 
			"%1\$s sra i nie spłukuje", 
			"%1\$s nie ustępuje miejsca starszym i schorowanym osobom w autobusie.", 
			"%1\$s nie odpowiada Dzień Dobry na ulicy", 
			"%1\$s nie mówi \"dziękuje\" po obiedzie", 
			"%1\$s spuszcza wodę tylko po kupie", 
			"%1\$s nie odkręca nakrętki przed wyrzuceniem plastikowej butelki", 
			"%1\$s dzieli przez zero", 
			"%1\$s je mięso w post", 
			"%1\$s używa licowanych bezpieczników", 
			"%1\$s zjadł święconkę przed Wielką Sobotą", 
			"%1\$s otworzył prezent przed gwiazdką", 
			"%1\$s nie wyciera butów", 
			"%1\$s wyjada wszystkie czekoladki z kalendarza adwentowego pierwszego grudnia", 
			"%1\$s nie chodzi do kościoła", 
			"%1\$s rysuje pożyczone płyty", 
			"%1\$s obraża papieża", 
			"%1\$s podbija własne tematy", 
			"%1\$s trzyma ręce w kieszeniach podczas rozmowy", 
			"%1\$s mlaska przy obiedzie", 
			"%1\$s nie przewija kaset przed oddaniem", 
			"%1\$s rozmawia w kościele", 
			"%1\$s wyciera szyjke jak pije po kimś", 
			"%1\$s sra do bidetu", 
			"%1\$s suszy papierowe ręczniki na kaloryferze", 
			"%1\$s śmieje się z cudzego nieszczęścia", 
			"%1\$s gwałci małe dzieci", 
			"%1\$s nie pomaga staruszkom przejść przez pasy", 
			"%1\$s przejeżdża na pomarańczowym", 
			"%1\$s nie wyciera dupy po sraniu", 
			"%1\$s nie zrobił laurki na dzień babci", 
			"%1\$s powiedział niewidomemu na przystanku, że jedzie dziewiętnastka, podczas gdy była to była siódemka", 
			"%1\$s kupuje dziewczęce majteczki na Allegro", 
			"%1\$s przykleja monety do asfaltu", 
			"%1\$s kopie działkę w Szabat.", 
			"%1\$s wyrzuca szklane butelki do pojemnika na plastik", 
			"%1\$s nie przestrzega przepisów BHP", 
			"%1\$s zostawia włosy na mydle", 
			"%1\$s nie spłukuje łanowców po kąpieli", 
			"%1\$s hałasuje podczas ciszy nocnej", 
			"%1\$s gra dalej na komputerze, mimo że powiedział mamie \"Już kończę!\" 2 godziny temu", 
			"%1\$s minusuje losowe wykopy", 
			"%1\$s obserwuje ten temat i poda was wszystkich do sądu za obrazę majestatu", 
			"%1\$s nie odłącza bezpiecznie urządzenia", 
			"%1\$s spojleruje chińskie bajki", 
			"%1\$s pluje do wody święconej", 
			"%1\$s kradnie mamie lajony", 
			"%1\$s to moderator /g/", 
			"%1\$s nie dzieli się drugim śniadaniem", 
			"%1\$s prosi kolegę o jednego czipsa i bierze pół paczki", 
			"%1\$s szkaluje papieża", 
			"%1\$s nie myje zębów", 
			"%1\$s wciąż używa Windows 7", 
			"%1\$s banuje losowych użytkowników Wykopu w stanie upojenia alkoholowego", 
			"%1\$s zapisuje miniaturki", 
			"%1\$s kradnie żarówki z klatki schodowej", 
			"%1\$s podkablował Ljuboję", 
			"%1\$s nie myje dupy przed analem", 
			"%1\$s plądruje piwnice sąsiadów", 
			"%1\$s popiera PiS", 
			"%1\$s dobiega do judasza w 2 sekundy", 
			"%1\$s maca bułki w sklepie", 
			"%1\$s ogląda kucyki", 
			"%1\$s nigdy się nie zgadza żeby kasjerka oddała grosika kiedy indziej", 
			"%1\$s nosi pantofle do dresów", 
			"%1\$s nie wie jak wyłączyć biblię", 
			"%1\$s pisze po ławkach", 
			"%1\$s nie zmienia obuwia w szkole", 
			"%1\$s wpadł w /fz/ i nie wie jak wyjść", 
			"%1\$s pije wode po pierogach", 
			"%1\$s śmiał się na Kac Wawa", 
			"%1\$s nosi buty na rzepy", 
			"%1\$s wyprzedza na podwójnej ciągłej", 
			"%1\$s przegrał z Najmanem", 
			"%1\$s prasuje spodnie dresowe w kanty", 
			"%1\$s nosi rurki na budowie", 
			"%1\$s jeździ na wakacje do Zgierza", 
			"%1\$s objada się pampuchami a potem wygląda tak jak wygląda", 
			"%1\$s twoja stara", 
			"%1\$s nie płakał po papieżu", 
			"%1\$s postuje na weszlo", 
			"%1\$s oddycha manualnie", 
			"%1\$s wita się przez próg", 
			"%1\$s uszkodził towar w sklepie po czym pospiesznie wyszedł", 
			"%1\$s trzyma widelec w prawej dłoni", 
			"%1\$s rozjebał paśnik", 
			"%1\$s rozlał kałamarz", 
			"%1\$s nie przyjął księdza po kolędzie", 
			"%1\$s mieszając herbatę dzwoni łyżeczką", 
			"%1\$s wycierał nos w rękaw", 
			"%1\$s zostawia buty w przejściu zamiast schować je do szafki", 
			"%1\$s nie gasi za sobą światła w ubikacji", 
			"%1\$s odstawia do lodówki pusty karton po mleku", 
			"%1\$s depcze partnerce po palcach podczas tańca", 
			"%1\$s nie odstawia w sklepie wózka na miejsce", 
			"%1\$s oblizuje talerz po bułce", 
			"%1\$s żuje gumę przy nauczycielce", 
			"%1\$s ma wielkiego pryszcza z białym czubkiem na brodzie i go nie wyciska", 
			"%1\$s pluje na chodnik", 
			"%1\$s sika do basenu", 
			"%1\$s zamyka ludziom drzwi przed nosem", 
			"%1\$s wchodzi do ZOO bez biletu", 
			"%1\$s nie opuszcza deski", 
			"%1\$s używa układu klawiatury 214", 
			"%1\$s mówi na grysik \"kasza manna\"", 
			"%1\$s skopiował swój lolifolder na VHS", 
			"%1\$s zesrał się w czasie swojego pogrzebu", 
			"%1\$s mówi \"na pole\"", 
			"%1\$s szkaluje Ducha Świętego", 
			"%1\$s korzysta z ofertu Zrembu zawsze na czasie", 
			"%1\$s nie wie co się w okół niego dzieje", 
			"%1\$s nie umie wejść na nocną", 
			"%1\$s nie szanuje swojej siostry", 
			"%1\$s nie sprząta odchodów po psie", 
			"%1\$s odpadł w 1/6 Ligi Mistrzów", 
			"%1\$s nie jest homoseksualny", 
			"%1\$s grymasi przy obiedzie", 
			"%1\$s zaspokoił Elfika32 w cewkę moczową", 
			"%1\$s pisze recenzje na Tanuki", 
			"%1\$s zabił Olafa Palme", 
			"%1\$s sra cegłami", 
			"%1\$s popiera ZUS", 
			"%1\$s jest cisgenderowy", 
			"%1\$s oblicza cotangensy Ojcu Rydzykowi", 
			"%1\$s nie wie że Yuri ma wielką dupe", 
			"%1\$s przeskakuje przez bramki w metrze", 
			"%1\$s śmieje się z Puchałke", 
			"%1\$s nie mówi cześć koleżankom", 
			"%1\$s jeździ amerykańskim autem", 
			"%1\$s rozmawia ze świadkami Jehowy", 
			"%1\$s pije wodę po ogórkach", 
			"%1\$s rozdaje Księgę Mormona", 
			"%1\$s używa Linuxa", 
			"%1\$s nie zmienia wody w akwarium", 
			"%1\$s gryzie rękę która go karmi", 
			"%1\$s gra w LoLa", 
			"%1\$s ogląda twardą pornografię", 
			"%1\$s robi zakupy w niedziele", 
			"%1\$s ogląda Big Bang Theory", 
			"%1\$s połyka rybie ości bez gryzienia", 
			"%1\$s zajada się majonezem prosto ze słoika", 
			"%1\$s proszony o polecenie chińskiej bajki rekomenduje Boku no Pico", 
			"%1\$s chodzi na manify", 
			"%1\$s pluje bezdomnym do zupy", 
			"%1\$s robi bonbe dupom", 
			"%1\$s pije herbatę z łyżeczką w środku", 
			"%1\$s nie chodził na religię w szkole", 
			"%1\$s inicjuje gównoburze", 
			"%1\$s popiera Korwina", 
			"%1\$s jeździ pociągiem na wstecznym", 
			"%1\$s nie daje napiwków", 
			"%1\$s ma szklanki w koszyczkach", 
			"%1\$s pisał \"chuj\" i \"cipa\" na szkolnych ławkach", 
			"%1\$s narkotyzuje się acodinem", 
			"%1\$s nie zapina pasów", 
			"%1\$s ma dywan na ścianie", 
			"%1\$s wyrzuca butelki zwrotne", 
			"%1\$s samowolnie oddalał się z lekcji biologii", 
			"%1\$s parkuje na kopertach", 
			"%1\$s saguje przypięte posty", 
			"%1\$s zagina rogi w książkach", 
			"%1\$s puszcza głośne wiatry i mówi że to w trawie coś piszczy", 
			"%1\$s nie daje na tacę", 
			"%1\$s zepsuł swojej mamie kwietnik, a winę zwalił na psa", 
			"%1\$s niszczy runo leśne", 
			"%1\$s nie zna się na zegarku", 
			"%1\$s rozwiesza ulotki z cenzopapą", 
			"%1\$s dał na tacę 10 zł i zażądał 9 reszty", 
			"%1\$s nie nauczył się na pamięć inwokacji z Pana Tadeusza", 
			"%1\$s nie chce jechać do babci", 
			"%1\$s wyjada ser z chizborgirów", 
			"%1\$s podbiera pieniądze z portmonetki babci", 
			"%1\$s napastuje kobiety w lesie", 
			"%1\$s nie chce jeść zupy", 
			"%1\$s nie pisał listów do świętego Mikołaja", 
			"%1\$s lubi zupę mleczną", 
			"%1\$s kupił mecz i przegrał", 
			"%1\$s złapał je wszystkie", 
			"%1\$s tasuje pod doujiny z Apple Bloom", 
			"%1\$s przeszkadza innym dzieciom w leżakowaniu", 
			"%1\$s zabrał babci dowód", 
			"%1\$s gnębił spierdoliny w szkole", 
			"%1\$s używa stylu Night", 
			"%1\$s brzydko się wyraża", 
			"%1\$s USUNĄŁ TO", 
			"%1\$s nie chce, żeby mama całowała go na dobranoc", 
			"%1\$s ma tajny folder na dyskietce", 
			"%1\$s nie widział nagich zdjęć elfika32", 
			"%1\$s przykleja gumę pod ławką", 
			"%1\$s podszywa się pod bł. Jana Pawła Drugiego i gwałci dzieci", 
			"%1\$s głosi kazania z ambony myśliwskiej", 
			"%1\$s czyta mangi od przodu", 
			"%1\$s szkaluje błogoslawionego Jana Pawła 2", 
			"%1\$s nosi Prządło na barana", 
			"%1\$s saguje ten temat", 
			"%1\$s wyjada mamie rodzyny z ciasta", 
			"%1\$s wszedł do internetu i nie umie wyjść", 
			"%1\$s wyrzucił Magika przez okno", 
			"%1\$s donosi do Kidprotect", 
			"%1\$s wywrócił globus na lewą stronę", 
			"%1\$s ukradł księdzu stułę i udaje kibica Fiorentiny", 
			"%1\$s w Wigilię mówi ludzkim głosem", 
			"%1\$s przedłużył kontrakt z Levy'm", 
			"%1\$s kradnie wanny z działek", 
			"%1\$s siorbie jedząc zupę", 
			"%1\$s kopie grzyby w lesie", 
			"%1\$s chodzi do kościoła w dresie", 
			"%1\$s pierze w rzece", 
			"%1\$s założył słabą stronę w internecie", 
			"%1\$s kradnie z pracy papier toaletowy", 
			"%1\$s trząsł stołem w czasie gry w bierki", 
			"%1\$s się garbi", 
			"%1\$s jeździ na gapę trolejbusem", 
			"%1\$s wyjada dziury w serze", 
			"%1\$s strzela z łuku do kur", 
			"%1\$s nie nosi majtek", 
			"%1\$s maluje jajka w Wigilię", 
			"%1\$s nie wie, że Jon umiera zadźgany przez braci z Marshem na czele", 
			"%1\$s kupuje chleb krojony", 
			"%1\$s śmieci na MS AGH i zwala na studentów", 
			"%1\$s kupuje bitcoiny w szczycie", 
			"%1\$s wozi drewno do lasu", 
			"%1\$s zabierał dzieciom samochody z gum Turbo i śmiał się przy tym jak zbir", 
			"%1\$s sprzedaje śnieg Eskimosom", 
			"%1\$s opowiada sprośnie dowcipy w obecności Elfika32", 
			"%1\$s pożycza w Providencie", 
			"%1\$s zjada 20 kg cebuli rocznie", 
			"%1\$s wyłącza biblię emotkami", 
			"%1\$s używa zasilacza Codegen", 
			"%1\$s wyłącza komputer zanim wyświetla się komunikat o możliwości bezpiecznego wyłączenia", 
			"%1\$s rucha wał z kołdry", 
			"%1\$s masturbuje się analnie przy rodzinnym obiedzie", 
			"%1\$s ściąga spodnie z torrentów", 
			"%1\$s nie wyłącza komórki na lekcjach", 
			"%1\$s nie wykupuje biletu w strefie płatnego parkowania", 
			"%1\$s ściągał na maturze", 
			"%1\$s nie klęka w kościele", 
			"%1\$s wpycha się w kolejki", 
			"%1\$s inkasuje opłatę za darmowe miejsca parkingowe", 
			"%1\$s wyrzuca śmieci w lesie", 
			"%1\$s sika do basenu", 
			"%1\$s błaźni się w tańcu", 
			"%1\$s nie zna hymnu", 
			"%1\$s nie umie w trójsiłę", 
			"%1\$s nie zatrzymuje się przed przejazdem kolejowym", 
			"%1\$s kradnie znicze z nagrobków", 
			"%1\$s parkuje na dwójce", 
			"%1\$s nie umie wyłączyć śledzika", 
			"%1\$s nie słucha RMF FM", 
			"%1\$s kobiety za życia nie ocenia", 
			"%1\$s nie wyłącza trybu stand-by w radiu kuchennym", 
			"%1\$s wozi psa w hundayu atosie 1.0 1993", 
			"%1\$s słucha tylko mamy i radia Z", 
			"%1\$s nie głosuje w wyborach parlamentarnych", 
			"%1\$s wie gdzie się podziały tamte prywatki", 
			"%1\$s wciąga rogale marcińskie nosem", 
			"%1\$s powiedział kasjerce, że w siatce jest pięć bułek. Było sześć", 
			"%1\$s kłamie", 
			"%1\$s kopie koty", 
			"%1\$s nie przepuszcza kobiet w drzwiach", 
			"%1\$s nasrał własnej matce pod drzwiami", 
			"%1\$s ogląda \"Pamiętniki z wakacji\"", 
			"%1\$s nakręcił i zamieścił w internecie psa bitego łopatą", 
			"%1\$s kibicuje Arce Gdyni", 
			"%1\$s zajebał mi ronaldo", 
			"%1\$s urolog nie polecam", 
			"%1\$s nie bierze ulotek", 
			"%1\$s chodzi do wegetariańskich restauracji i prosi o schabowe", 
			"%1\$s przyklepuje groszek ziemniakami", 
			"%1\$s składając zamówienie podszczypuje kelnerki", 
			"%1\$s kupuje koncentrat zamiast keszupu mikado", 
			"%1\$s zajmuje toalety dla niepełnosprawnych", 
			"%1\$s ma dwie skrzynki na bezpieczniki", 
			"%1\$s kłóci się o grosik reszty", 
			"%1\$s uprawia seks bez zabezpieczeń", 
			"%1\$s obnaża się w miejscach publicznych. Zapytany, dlaczego to robi, wznosi wzrok ku niebu, wzrusza ramionami i z charakterystycznym dla niego, niewzruszonym optymizmem mówi \"wielkie mi mecyje\"", 
			"%1\$s gra sam ze sobą w szachy i przegrywa", 
			"%1\$s postawił serwer. Na dywanie", 
			"%1\$s wpłacił dotację na kurahena", 
			"%1\$s wyrzucał przygotowane przez mamę kanapki i kupował batoniki w szkolnym sklepiku", 
			"%1\$s odkurza w sobotę o 8 rano", 
			"%1\$s głosował na Huberta Humphreya i zabił Jezusa", 
			"%1\$s zgłosił się do kwestowania podczas Wielkiej Orkiestry Świątecznej Pomocy, po czym przywłaszczył sobie zawartość puszki", 
			"%1\$s ma zacięty caps lock", 
			"%1\$s bił koleżanki skakanką", 
			"%1\$s wypychał kieszenie ołówkami w IKEA i zabierał je do domu", 
			"%1\$s nie kliknął brzuszka pajacyka", 
			"%1\$s kradnie pączki Patrycji", 
			"%1\$s jeździ gimbusem na gapę", 
			"%1\$s strzela dla dziewczyn ze staników", 
			"%1\$s nie wykupował obiadów w szkolnej stołówce, a potem przy okienku twierdził, że zgubił karteczkę", 
			"%1\$s jest synem swojego brata", 
			"%1\$s nie segreguje śmieci", 
			"%1\$s chodzi ścieżką rowerową", 
			"%1\$s nie zjada skórek od chleba", 
			"%1\$s zrobił wszystkie popmki", 
			"%1\$s zgrał internet na dyskietke", 
			"%1\$s podglądał kuzynkę w wannie", 
			"%1\$s poszedł do ZOO i go małpy wyśmiały", 
			"%1\$s dokarmia zwierzęta w ZOO kiedy pracownicy nie patrzą", 
			"%1\$s pozwala spadać dobrym tematom", 
			"%1\$s pisze \"puhar\" przez samo \"h\"", 
			"%1\$s łapał w podstawówce koleżanki za siusię", 
			"%1\$s krzywi się do małych dzieci", 
			"%1\$s smaruje klamki kupą", 
			"%1\$s wrzuca sąsiadom kamienie do skrzynek na listy", 
			"%1\$s obsikuje deskę i spuszcza wodę przy otwartej klapie", 
			"%1\$s sam zrajdował 370chan.lt/b/", 
			"%1\$s szkaluje papieża na youtube i zwala wine za to na fora katolickie", 
			"%1\$s nie przestrzega netykiety", 
			"%1\$s podbija z czternastej", 
			"%1\$s wymacywał Tazosy w paczkach Lays", 
			"%1\$s wsypywał sól czanów do cukierniczki", 
			"%1\$s lurkuje /4/", 
			"%1\$s podrabiał podpis rodziców pod uwagami w dzienniczku", 
			"%1\$s mocno zmasakrował młodego lewaka", 
			"%1\$s mówi keczap zamiast keczup", 
			"%1\$s waży śmietanę w zupie", 
			"%1\$s rozwalił słonecznik pod ławką", 
			"%1\$s postuje o 21:37", 
			"%1\$s bije w szczepionkę", 
			"%1\$s nakremował klamki w tłusty czwartek", 
			"%1\$s trzyma ręce w kieszeniach jak rozmawia z ludźmi", 
			"%1\$s niszczy w lesie niejadalne grzyby", 
			"%1\$s nie chciał karnego po trzech rożnych", 
			"%1\$s rzuca w pomnik", 
			"%1\$s naśmiewa się z ludzi którzy mają gorzej", 
			"%1\$s kupuje papierosy od ruskich", 
			"%1\$s parkuje na miejscu dla niepełnosprawnych", 
			"%1\$s sika do zlewu", 
			"%1\$s nie umie wejść na ruski", 
			"%1\$s liczy ile pierogów kto zjadł a później wypomina!", 
			"%1\$s wzywa straż pożarną bez powodu", 
			"%1\$s maca chipsy w poszukiwaniu tazos", 
			"%1\$s nie wyłącza sprzętów elektronicznych podczas burzy", 
			"%1\$s wszedł podczas deszczu do niezabezpieczonej stacji transformatorowej", 
			"%1\$s czyta streszczenia zamiast lektur", 
			"%1\$s ksuje na spotach", 
			"%1\$s wpierdala grochową przed szkołą", 
			"%1\$s jebał w dupę bez prezerwatywy", 
			"%1\$s pali włosy na nogach w szatni od wfu", 
			"%1\$s słucha Firmy przy rodzicach", 
			"%1\$s pokazał środkowy palec na koncercie Tibii", 
			"%1\$s chodzi na wagary", 
			"%1\$s wandalizuje wikipedie", 
			"%1\$s przykleja włosy do mydła", 
			"%1\$s zostawia puste rolki po papierze toaletowym", 
			"%1\$s nie płakał po papieżu", 
			"%1\$s bagatelizuje ostrzeżenia epidemiologiczne", 
			"%1\$s podgląda sąsiadkę przez okno i wali o tym konia", 
			"%1\$s oszukał tramwaj-kupił bilet i poszedł pieszo", 
			"%1\$s podbiera jajka z kurnika", 
			"%1\$s pisał dokumenty w comic sans", 
			"%1\$s wyciągał taśmy z kaset VHS", 
			"%1\$s przeszkadza kasjerkom liczyć pieniądze", 
			"%1\$s nie daje suchego chleba dla konia", 
			"%1\$s nie segreguje śmieci", 
			"%1\$s postuje cenzo na wykopie", 
			"%1\$s odpowiada na trolla", 
			"%1\$s bierze kredyt w SKOKu", 
			"%1\$s zgwałcił pasiekę", 
			"%1\$s nie zmienił czasu na letni", 
			"%1\$s zjada swój kał", 
			"%1\$s to twoja stara", 
			"%1\$s pluł na moherowe babcie pod krzyżem", 
			"%1\$s zamiata śmieci pod dywan", 
			"%1\$s wierzy w zamach w Smoleńsku", 
			"%1\$s kibicuje Legii", 
			"%1\$s wierzy w mistrzostwo Legii", 
			"%1\$s kibicuje Lechowi", 
			"%1\$s wierzy w mistrzostwo Lecha", 
			"%1\$s kibicuje Wiśle", 
			"%1\$s wierzy, że Wisła się utrzyma", 
			"%1\$s nie wierzy w boga", 
			"%1\$s postuje w wątkach o muzyce myśląc że to kogoś obchodzi", 
			"%1\$s wierzy w boga", 
			"%1\$s jak był mały spadł z dywanu na podłogę i złamał żebra", 
			"%1\$s czyta cały ten temat", 
			"%1\$s jest cały w kale", 
			"%1\$s nie odprowadza składek na ZUS", 
			"%1\$s kompiluje jądra. Ojca", 
			"%1\$s kradnie węgiel Ślązakom", 
			"%1\$s grabi zagrabione", 
			"%1\$s gwałci się sam", 
			"%1\$s ogląda Czarodziejkę z Księżyca", 
			"%1\$s tańczy parapara z własnym kotem", 
			"%1\$s rozmawial glosno na lekcji", 
			"%1\$s nie jadł drugiego śniadania", 
			"%1\$s odpisywał prace domowe na przerwie", 
			"%1\$s nie pisze postów w epickim", 
			"%1\$s wysyła emacsem przez sendmail", 
			"%1\$s strzelał z czuba", 
			"%1\$s napluł na korytarzu", 
			"%1\$s umazał gównem portrety naszych przywódców", 
			"%1\$s pociął ostrzem od temperówki 20 kurtek w szatni i mu się to upiekło", 
			"%1\$s wali konia codziennie o 21:37", 
			"%1\$s wciąż nie wie czy grzyby to bardziej rośliny czy zwierzęta", 
			"%1\$s podchodzi do losowych przechodniów, kopie w kostkę, po czym spierdala z szyderczym śmiechem", 
			"%1\$s wraz z kolegą przyniósł na lekcję ślimaki i puszczał je po szafie", 
			"%1\$s nie wyłącza jednostki centralnej podczas burzy", 
			"%1\$s obraża Zalgo", 
			"%1\$s zapomina hasła do usuwania postów", 
			"%1\$s nie odkłada butów na półkę", 
			"%1\$s je pitcę z sokiem mailnowym super odlotowym", 
			"%1\$s pruka w autobusie i patrzy z wyrzutem na współpasażera", 
			"%1\$s wrzuca obspermione majtki matce prosto w pralkę", 
			"%1\$s obraża papieża na wykopie", 
			"%1\$s nie ustępuje pierwszeństwa pieszym na pasach", 
			"%1\$s dostaje bana na karachanie :(", 
			"%1\$s lekceważy regulamin karachan.org :(", 
			"%1\$s wyrzuca kanapki do szkoły a mamie mówi że zjadł", 
			"%1\$s rzadko zmienia skartpetki i bielizne", 
			"%1\$s odgryza czarną końcówkę od banana", 
			"%1\$s siada przy sikaniu", 
			"%1\$s pierdzi przy laniu", 
			"%1\$s zaopatruje Stana L. w fioletową ambrozję. Pijackie eldorado zdaje się nie mieć końca", 
			"%1\$s postuje chociaż nie ma pomysła na treść posta", 
			"%1\$s podczas masturbacji udaje orgazmy", 
			"%1\$s nie odrobił zadania domowego tłumacząc się, że opłakiwał śmierć papieża", 
			"%1\$s dał 5 zł", 
			"%1\$s ociera się o kobiety w autobusie", 
			"%1\$s to Peja z Poważnej", 
			"%1\$s podkablował Ljuboję", 
			"%1\$s wyjada karme dla kota", 
			"%1\$s nie dał pasty termoprzewodzącej przy montażu nowego procesora", 
			"%1\$s nie zakręca wody w kranie podczas mycia zębów", 
			"%1\$s wchodzi bez pukania", 
			"%1\$s na 3 maja chodzi po mieście i kradnie flagi", 
			"%1\$s nie świętuje urodzin Sunny", 
			"%1\$s nie wysypuje chipsów na talerz", 
			"%1\$s wylizuje miske psu", 
			"%1\$s myje ojcu plecy", 
			"%1\$s ogląda shoneny", 
			"%1\$s wali gruchę w pokoju rodziców", 
			"%1\$s ogląda How I Met Your Mother", 
			"%1\$s rucha psa jak sra", 
			"%1\$s je guwno", 
			"%1\$s na lekcji religii z szyderczym uśmiechem powiedział do katechetki: \"papież tak bardzo martwy\" po czym wyskoczył z okna", 
			"%1\$s nie opuszcza deski sedesowej bo załatwieniu potrzeby fizjologicznej", 
			"%1\$s wrzuca oc na kwejka", 
			"%1\$s nasrał koleżance do buta", 
			"%1\$s nie umył rąk po masturbacji", 
			"%1\$s pod przymusem odmówienia modlitwy od babci, ukląkł i w myślach powtarzał \"huj huj huj\" zamiast słów modlitwy", 
			"%1\$s głupio podśmiechiwał w muzeum holocaustu", 
			"%1\$s spóźnił się na zajęcia i było można wyczuć od niego zapach palonych zapałek", 
			"Na sesjach rpg %1\$s dopisywał swojej postaci fikcyjne umiejętności", 
			"%1\$s nie myje po sobie talerzy", 
			"%1\$s chodzi w bluzach \"JP\", a babci mówi, że to jest skrót od Jan Paweł, żeby mu dawała pieniądze na tace, które przeznacza na gazowane napoje i Top Chipsy", 
			"%1\$s pije piwo pod sklepem, mimo iż widnieje tam napis zakazujący owej czynności", 
			"%1\$s rozgazowuje Colę w sklepie", 
			"%1\$s nie mówi \"na zdrowie\" gdy ktoś kichnie", 
			"%1\$s chodził na wagary w podstawówce", 
			"%1\$s nie dostał licencji na grę w pucharach", 
			"%1\$s popiera dzielenie punktów po sezonie zasadniczym", 
			"%1\$s kopiuje %1\$s z pierwszego postu bo nie chce mu sie pisac samemu", 
			"%1\$s uratował dziecko z pożaru. A potem się obudził", 
			"%1\$s nie pomaga osobom na wózku inwalidzkim w wejściu po schodach", 
			"%1\$s gotuje parówki nie zdejmując folii", 
			"%1\$s sra ludziom na wycieraczki", 
			"%1\$s puszcza cichacze i zgania na osoby obok niego", 
			"%1\$s założył własną firmę ale go z niej zwolniono", 
			"%1\$s używa kodów grając w sapera", 
			"%1\$s nie pomaga użytkownikom forum w problemach", 
			"%1\$s dojebał Napoleonowi", 
			"%1\$s wyrywa muchom skrzydełka", 
			"%1\$s jeźdźi środkowym pasem", 
			"%1\$s skarży pani", 
			"%1\$s przyjmuje ciało Chrystusa nie podchodząc uprzednio do spowiedzi", 
			"%1\$s pojmał nowocioty", 
			"%1\$s nie mówi wszystkich grzechów przy spowiedzi", 
			"%1\$s wykupił Polonię Warszawa", 
			"%1\$s biega boso po domu, mimo że mama prosi aby założył kapcie", 
			"%1\$s rozpisuje diety na forach", 
			"%1\$s wyrzuca kubki od jogurtów nie wyskrobując do końca", 
			"%1\$s wykopuje informacje nieprawdziwe", 
			"%1\$s wyjada sarnom z paśnika", 
			"%1\$s sprawdza czy hajs się zgadza", 
			"%1\$s kurwi się czanmową", 
			"%1\$s głosował na Stana Tymińskiego", 
			"%1\$s pali w miejscach publicznych", 
			"%1\$s wrzuca do galerii nie odwrócone zdjęcia", 
			"%1\$s nie rozumie dowcipu a babie i frezarce", 
			"%1\$s zbiera wungiel przy torach", 
			"%1\$s nie przeprasza rywala po faulu", 
			"%1\$s sprzedaje obwarzanki na targu nie mając stosownego zezwolenia", 
			"%1\$s myśli że Sosnowiec jest na Śląsku", 
			"%1\$s klepie koleżanki po tyłku, zapytany dlaczego odpowiada że jest samcem alfa i mu wolno", 
			"%1\$s bierze na poczcie numerki do kilku okienek naraz", 
			"%1\$s grzebie sobie w dupie w miejscach publicznych", 
			"%1\$s psuje swój licznik neodymem", 
			"%1\$s dokonał ludobójstwa na Wołyniu", 
			"%1\$s dosyła skany za 10 tysięcy", 
			"%1\$s kładzie kamienie na szynach", 
			"%1\$s kupuje pliki na chomikuju.", 
			"%1\$s pali w piecu oponami", 
			"%1\$s raiduje kro­chana", 
			"%1\$s rzadko się goli i wygląda niechlujnie", 
			"%1\$s składuje azbest z starych fabryk w piwnicy dziadka", 
			"%1\$s obgryza paznokcie u nóg", 
			"%1\$s puszcza głośno muzykę z telefonu", 
			"%1\$s pije herbatę z łyżką w szklance", 
			"%1\$s rozdeptuje ślimaki po deszczu", 
			"%1\$s nie potrafi się cieszyć z małych rzeczy", 
			"%1\$s wchodzi mi do wanny [cool]", 
			"%1\$s fapie do chińskich bajek", 
			"%1\$s nie przyznaje się do bycia polakiem", 
			"%1\$s nie myje zębów na noc", 
			"%1\$s mówi psy na policję", 
			"%1\$s nie lubi Dragon Balla", 
			"%1\$s nosi dwie różne skarpetki", 
			"%1\$s wstaje po południu", 
			"%1\$s odgrzewa w mikrofalówce", 
			"%1\$s nie śpiewał hymnu", 
			"%1\$s chodzi nieuczesany", 
			"%1\$s nie miał stroju na wf", 
			"%1\$s nie przekazał 1% na chore dzieci", 
			"%1\$s obraża się kiedy przegrywa", 
			"%1\$s dokucza dziewczynom", 
			"%1\$s nie kupuje polskich produktów", 
			"%1\$s ciągnie koleżanki za włosy", 
			"%1\$s nie odwzajemnia uśmiechu", 
			"%1\$s rozpierdolił dwie pasieki", 
			"%1\$s zajada się smalcem", 
			"%1\$s kradnie czereśnie", 
			"%1\$s grzebie sobie w dupie", 
			"%1\$s nie umie przepraszać", 
			"%1\$s nigdy nie podaje piłki", 
			"%1\$s woli wyrzucić niż oddać koledze", 
			"%1\$s chodzi po trawnikach", 
			"%1\$s ma pirackiego Windowsa", 
			"%1\$s zadziera nosa", 
			"%1\$s ma zrośnięte brwi", 
			"%1\$s ma brudny kołnierz", 
			"%1\$s pije piwo z sokiem", 
			"%1\$s ma wysoki cholesterol", 
			"%1\$s przejechał kota sąsiada", 
			"%1\$s zaczepia młode dziewczyny", 
			"%1\$s przeszedł Mario Bros w lewo", 
			"%1\$s utopił swoje Simy", 
			"%1\$s mieszka u mamy", 
			"%1\$s ma włosy na plecach", 
			"%1\$s robi grilla na balkonie", 
			"%1\$s głosuje na PO", 
			"%1\$s nie wymienia szczoteczki do zębów", 
			"%1\$s śmiał się na wychowaniu do życia w rodzinie", 
			"%1\$s grał w karty na religii", 
			"%1\$s palił papierosy w szkolnej toalecie", 
			"%1\$s nie oszczędza prądu", 
			"%1\$s wymusza pierszeństwo", 
			"%1\$s przechodzi przez ulicę w miejscach niedozwolonych", 
			"%1\$s dzwoni na policję i robi głupie żarty", 
			"%1\$s nie zostawia napiwków", 
			"%1\$s słucha Radia Maryja", 
			"%1\$s uchylał się od służby wojskowej", 
			"%1\$s ukrywa swoje dochody", 
			"%1\$s nie chodzi na wywiadówki", 
			"%1\$s zapomniał nakarmić kota", 
			"%1\$s nie pamięta czy wyłączył żelazko", 
			"%1\$s nie lubi zwierząt", 
			"%1\$s sika do zlewu", 
			"%1\$s je kanapki z serem i szynką", 
			"%1\$s nie notował na lekcji", 
			"%1\$s wykorzystał wszystkie nieprzygotowania w pierwszym tygodniu", 
			"%1\$s rzuca papierki na ulicę", 
			"%1\$s nie sprząta po swoim psie", 
			"%1\$s przełącza dzieciom bajki", 
			"%1\$s ma trudny charakter", 
			"%1\$s nie kosi trawnika", 
			"%1\$s PISZE WIELKIMI LITERAMI", 
			"%1\$s nie wie kto to Mickiewicz", 
			"%1\$s pluje z okna na ludzi", 
			"%1\$s nie szanuje homoseksualistów", 
			"%1\$s wciąga rogale, oficjalnie do środka", 
			"%1\$s z tyłu zobaczył nasz ratusz", 
			"%1\$s ma platynowe konto na kurahenie", 
			"%1\$s wchodzi na komixxy i uważa je za zabawne", 
			"%1\$s jeździ Solarisem", 
			"%1\$s podpala Solarisy", 
			"%1\$s zakopuje znaleziska o spalających się Solarisach", 
			"%1\$s ma multikonta na wykopie", 
			"%1\$s pisze \"Cię\" w internecie", 
			"%1\$s strzelał do polaków", 
			"%1\$s streamuje chińskie bajki", 
			"%1\$s wącha przestrzenie między palcami stóp", 
			"%1\$s ściąga na dysk chińskie bajki", 
			"%1\$s obrzygał ojca podczas rodzinnego objadu", 
			"%1\$s sięgał ręką gdy Testo podawał pomarańczę", 
			"%1\$s rzucał czereśniami w przejeżdżające samochody", 
			"%1\$s uważa się za lepszego od Jana Pawła II", 
			"%1\$s siada na miejscu dla ciężarnej kobiety i odwraca głowę", 
			"%1\$s pije redbulla i udaje Magika", 
			"%1\$s z całym wózkiem zakupów ustawia się przy kasie \"do dziesięciu produktów\"", 
			"%1\$s odpowiada na maile z Nigerii", 
			"%1\$s oblał mamie białą bluzkę sokiem z czarnej porzeczki", 
			"%1\$s wrzuca plastikowe butelki do pojemnika na papier", 
			"%1\$s nie wie na czym polega spalony", 
			"%1\$s wyjada porzeczki sąsiadom, a zapytany kto to zrobił odpowiada, że Duch Święty", 
			"%1\$s wyrzuca butelki do pojemnika z papierem", 
			"%1\$s przed masturbacją nie wyłancza kamerkę internetową", 
			"%1\$s zakopuje swoje znaleziska", 
			"%1\$s przewraca żółwie na grzbiet", 
			"%1\$s zjada świeczki z tortu", 
			"%1\$s wkłada szpilki do dziurek od klucza", 
			"%1\$s podgląda nagą młodszą siostrę, zapytany co robi odpowiada że kontempluje naturę", 
			"%1\$s podpala mrówki szkłem powiększającym", 
			"%1\$s zamawia za pobraniem po czym nie odbiera przesyłki", 
			"%1\$s dzwoni na koszt rozmówcy", 
			"%1\$s zatykał pyrą rurę wydechową w polonezie ojca", 
			"%1\$s przywiązuje kotom puszki do ogonów", 
			"%1\$s zajebał mi szlugi", 
			"%1\$s wsiada do pociągu byle jakiego", 
			"%1\$s przegrał w Jumanji", 
			"%1\$s nie wie gdzie jest Wally", 
			"%1\$s to %1\$s tamto xD", 
			"%1\$s używa margaryny zamiast masła", 
			"%1\$s podjada między posiłkami", 
			"%1\$s zjada kozy z nosa", 
			"%1\$s mierzy rezystancję metodą techniczną omomierzem", 
			"%1\$s pełen agresji rzucał śnieżkami w sąsiedzkie okna", 
			"%1\$s uważa, że \"dzień świra\" to komedia", 
			"%1\$s wyrywa lachony na trabanta", 
			"%1\$s nie umie obliczać modułu liczb urojonych", 
			"%1\$s używa myszki kulkowej", 
			"%1\$s przeniósł się w czasie i ukrzyżował Jezusa Chrystusa", 
			"%1\$s był za ACTA", 
			"%1\$s chciał zjeść ślimaka ale mu uciekł", 
			"%1\$s zakłada thready \"prawaki vs lewaki\" zaśmiewając się przy tym do monitora", 
			"%1\$s odpala strony porno w wystawowych komputerach w MediaMarkt po czym oddala się w popłochu", 
			"%1\$s wychodzi z restauracji bez płacenia", 
			"%1\$s wyjada w Biedronce nadzienie z Oreo", 
			"%1\$s wystrzeliwał w sufit z rurki od długopisu namoczone kawałki czerwonej krepy", 
			"%1\$s podczas zabawy na świetlicy plastikowym samolotem, dźwiękiem pękającego plastiku zwrócił uwagę opiekunki i na pytanie co się stało, odpowiedział, że to tak już było", 
			"%1\$s strzela z wiatrówki do psa sąsiada", 
			"%1\$s je chipsy podczas grania na playstation", 
			"%1\$s zmienia tapety w telefonie matki bez pozwolenia", 
			"%1\$s je chipsy zimą", 
			"%1\$s nie szanuje zieleni", 
			"%1\$s nie wytrzepał butów po wyjściu z piaskownicy", 
			"%1\$s odkamienia czajnik octem", 
			"%1\$s pluje sobie w brodę", 
			"%1\$s puszcza muzykę z komórki jadąc autobusem", 
			"%1\$s kroi jedzenie widelcem", 
			"%1\$s dosypywał trutki do karmnika", 
			"%1\$s przebija opony sąsiadom", 
			"%1\$s udaje, że coś mu upadło, schyla się po to, a tak na prawdę chodzi mu o to żeby zajrzeć koleżance pod spódnice", 
			"%1\$s płaci za bułki banknotami 100-złotowymi", 
			"%1\$s podłożył koledze pierdzącą poduszke na krzesło i później się wszyscy z niego nabijali że puścił bąka", 
			"%1\$s nie zwalnia pamięci po dynamicznym jej przydzieleniu", 
			"%1\$s głośno chrupie podczas seansu filmowego", 
			"%1\$s trzyma hasła użytkowników wykop.pl w postaci jawnej", 
			"%1\$s na klasówce z matematyki odwraca kartkę na drugą stronę żeby nikt nie ściągnął", 
			"%1\$s ostentacyjnie spożywa mięsne pokarmy w piątki", 
			"%1\$s nosi słuchawki na odwrót", 
			"%1\$s nie nosi krawatu", 
			"%1\$s śmiał się na pogrzebie papieża", 
			"%1\$s depcze trawniki", 
			"%1\$s nie sprząta po psie", 
			"%1\$s nie segreguje odpadów", 
			"%1\$s zjada kozy z nosa", 
			"%1\$s wali pod cycki Aralki", 
			"%1\$s obraża papieża i wmawia wszystkim że to karachan.gov", 
			"%1\$s nie bierze prysznica przed wejściem na basen", 
			"%1\$s w kościele w momencie kiedy ksiądz podchodzi z tacą mówi: nie, dziękuję", 
			"%1\$s wyjada siano spod wigilijnego obrusa", 
			"%1\$s popiera Gimpera", 
			"%1\$s zgłosił filmik Gimperra", 
			"%1\$s pisze pozytywne komentarze pod filmikami Gimbera", 
			"%1\$s lurkuje Karachan.gov na stylu Night", 
			"%1\$s wybijał szyby vlogerom", 
			"%1\$s sam sobie wysyła zlewy i zwala winę na forum obrazkowe o kupie", 
			"%1\$s zaznacza do usunięcia epickie nitki", 
			"%1\$s zapisał tę nitkę do .mht", 
			"%1\$s nie umie zapisywać nitek", 
			"%1\$s nie umie zablokować zakodowanego tła", 
			"%1\$s sprawdza limity bumpowania sagując");
	}

	public function onPost(&$eventData)
	{
		if ($this->mitsuba->common->startsWith($eventData['email'], "#szkaluje"))
		{
			$szkaluj = explode(" ", $eventData['email'], 2);
			$szkalowany = "OP";
			if (count($szkaluj) == 2)
			{
				$szkalowany = $szkaluj[1];
			}
			$szkaluj_text = sprintf($this->szkaluj_array[array_rand($this->szkaluj_array)], $szkaluj[1]);
			$szkaluj_code = "<+<span style='color: violet; font-weight: bold;'>".$szkaluj_text."</span>+>";
			$eventData['comment'] = $szkaluj_code."\n".$eventData['comment'];
			$eventData['email'] = "";
		}
	}
	
	public function getName()
	{
		return "#szkaluję";
	}
	
	public function getUpdateURL()
	{
		return null;
	}
}
?>